version: '3.8'

services:
  exec-dash:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount data directory if you need persistent storage
      - ./data:/app/data:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4200/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - exec-dash-network

networks:
  exec-dash-network:
    driver: bridge
